# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
# project: x77

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
# shortpath: /scratch/v45

queue: normal
ncpus: 48
jobfs: 10GB
mem: 192GB

walltime: 00:30:00
jobname: 1deg_jra55do_ryf_bling

model: access-om3

# exe: /g/data/ik11/spack/0.20.1/opt/linux-rocky8-cascadelake/intel-2021.6.0/access-om3-main-lxbeca7/bin/access-om3-MOM6-CICE6
exe: /g/data/tm70/ds0092/model/access-om3/Release/bin/access-om3-MOM6-CICE6
input: 
    - /g/data/ik11/inputs/access-om3/0.x.0/1deg/share # shared grids and topography
    - /g/data/ik11/inputs/access-om3/0.x.0/1deg/mom # grids, ICs etc
    - /g/data/ik11/inputs/access-om3/0.x.0/1deg/cice # grids, ICs etc
    - /g/data/ik11/inputs/access-om3/0.x.0/share/meshes/JRA55do-ESMFmesh.nc # mesh for JRA55-do stream
    - /g/data/ik11/inputs/JRA-55/RYF/v1-4 # datm and drof JRA55-do streams data
    - /g/data/tm70/ds0092/model/inputs/access-om3/Alk.nc # BLING init file
    - /g/data/tm70/ds0092/model/inputs/access-om3/grid_spec.nc # needed for data_override
    - /g/data/tm70/ds0092/model/inputs/access-om3/init_ocean_cobalt_phyto_biomass.res.nc
    - /g/data/tm70/ds0092/model/inputs/access-om3/init_ocean_cobalt.res.nc # BLING init file
    - /g/data/tm70/ds0092/model/inputs/access-om3/ocean_mosaic.nc # needed for data_override
    - /g/data/tm70/ds0092/model/inputs/access-om3/Preind_DIC.nc # BLING init file
    - /g/data/tm70/ds0092/model/inputs/access-om3/RYF.co2.test.1990_1991.nc # BLING bogus co2 datm stream
    - /g/data/tm70/ds0092/model/inputs/access-om3/Soluble_Fe_Flux_PI.nc # BLING dry_dep_fed_flux for data override
    - /g/data/tm70/ds0092/model/inputs/access-om3/woa13_all_o_annual_01.nc # BLING init file
    - /g/data/tm70/ds0092/model/inputs/access-om3/woa13_all_p_annual_01.nc # BLING init file
 
collate: false
runlog: false

userscripts:
    setup: ./setup_cice_restarts.sh
    archive: ./archive_cice_restarts.sh

modules:
  use:
      - /g/data/ik11/spack/0.20.1/modules/access-om3/0.x.0/linux-rocky8-cascadelake
  load:
      - intel-compiler/2021.6.0
      - openmpi/4.1.4
      - parallelio/2.5.10
