format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/tm70/ds0092/model/dev/access-om3-gtracer/.spack-env/view/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: a552bb930c86df92cf883e3aaf8129bf
    md5: 1b1e5d28a25aeee06ebcfcda2dde2f94
