format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/tm70/ds0092/model/access-om3/Release/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: 4d5adf5212f4a86e4cccd088fc256130
    md5: 7e8f09ea185c37e0f63b2aed1c8b3bd6
