format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6:
  fullpath: /g/data/tm70/ds0092/model/access-om3/Release/bin/access-om3-MOM6-CICE6
  hashes:
    binhash: edee43f1a6d8731c16284d349a83b068
    md5: 553777f4bdfb8b877f80d7b97ef0e634
